package futuristicfactories.common.registry;

public interface IFFRegistryNames {

    String REGISTRY_FOLDER_ORE_CHUNK = "ore_chunk/";
    String REGISTRY_FOLDER_ORE_CLUMP = "ore_clump/";
    String REGISTRY_FOLDER_ORE_CRYSTAL = "ore_crystal/";
    String REGISTRY_FOLDER_ORE_TINY_CRYSTAL = "ore_tiny_crystal/";
    String REGISTRY_FOLDER_ORE_DUST = "ore_dust/";
    String REGISTRY_FOLDER_ORE_DIRTY_DUST = "ore_dirty_dust/";
    String REGISTRY_FOLDER_ORE_FRAGMENT = "ore_fragment/";
    String REGISTRY_FOLDER_ORE_PIECE = "ore_piece/";
    String REGISTRY_FOLDER_ORE_PILE = "ore_pile/";
    String REGISTRY_FOLDER_ORE_RESIDUAL = "ore_residual/";
    String REGISTRY_FOLDER_ORE_SAND = "ore_sand/";
    String REGISTRY_FOLDER_ORE_SHARD = "ore_shard/";
    String REGISTRY_FOLDER_INGOT = "ingot/";
    String REGISTRY_FOLDER_NUGGET = "nugget/";

    String REGISTRY_NAME_ALUMINUM_MATERIAL = "aluminum";
    String REGISTRY_NAME_COPPER_MATERIAL = "copper";
    String REGISTRY_NAME_LEAD_MATERIAL = "lead";
    String REGISTRY_NAME_NICKEL_MATERIAL = "nickel";
    String REGISTRY_NAME_SILVER_MATERIAL = "silver";
    String REGISTRY_NAME_TIN_MATERIAL = "tin";
    String REGISTRY_NAME_IRON_MATERIAL = "iron";
    String REGISTRY_NAME_GOLD_MATERIAL = "gold";

    String REGISTRY_NAME_ORE = "_ore";
    String REGISTRY_NAME_BLOCK = "_block";
    String REGISTRY_NAME_INGOT = "_ingot";
    String REGISTRY_NAME_NUGGET = "_nugget";

    String REGISTRY_NAME_ORE_CHUNK = "_ore_chunk";
    String REGISTRY_NAME_ORE_CLUMP = "_ore_clump";
    String REGISTRY_NAME_ORE_CRYSTAL = "_ore_crystal";
    String REGISTRY_NAME_ORE_TINY_CRYSTAL = "_ore_tiny_crystal";
    String REGISTRY_NAME_ORE_DUST = "_ore_dust";
    String REGISTRY_NAME_ORE_DIRTY_DUST = "_ore_dirty_dust";
    String REGISTRY_NAME_ORE_FRAGMENT = "_ore_fragment";
    String REGISTRY_NAME_ORE_PIECE = "_ore_piece";
    String REGISTRY_NAME_ORE_PILE = "_ore_pile";
    String REGISTRY_NAME_ORE_RESIDUAL = "_ore_residual";
    String REGISTRY_NAME_ORE_SAND = "_ore_sand";
    String REGISTRY_NAME_ORE_SHARD = "_ore_shard";

    String REGISTRY_NAME_CRUSHING = "crushing";

    String REGISTRY_NAME_MACHINE = "_machine";


    // REGISTRY_NAME_ORE
    String REGISTRY_NAME_ALUMINUM_ORE = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_COPPER_ORE = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_LEAD_ORE = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_NICKEL_ORE = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_SILVER_ORE = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_TIN_ORE = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE;

    // REGISTRY_NAME_BLOCK

    String REGISTRY_NAME_ALUMINUM_BLOCK = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_COPPER_BLOCK = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_LEAD_BLOCK = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_NICKEL_BLOCK = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_SILVER_BLOCK = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_TIN_BLOCK = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_BLOCK;

    // REGISTRY_NAME_INGOT
    String REGISTRY_NAME_ALUMINUM_INGOT = REGISTRY_FOLDER_INGOT + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_COPPER_INGOT = REGISTRY_FOLDER_INGOT + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_LEAD_INGOT = REGISTRY_FOLDER_INGOT + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_NICKEL_INGOT = REGISTRY_FOLDER_INGOT + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_SILVER_INGOT = REGISTRY_FOLDER_INGOT + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_TIN_INGOT = REGISTRY_FOLDER_INGOT + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_INGOT;

    // REGISTRY_NAME_NUGGET
    String REGISTRY_NAME_ALUMINUM_NUGGET = REGISTRY_FOLDER_NUGGET + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_COPPER_NUGGET = REGISTRY_FOLDER_NUGGET + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_LEAD_NUGGET = REGISTRY_FOLDER_NUGGET + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_NICKEL_NUGGET = REGISTRY_FOLDER_NUGGET + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_SILVER_NUGGET = REGISTRY_FOLDER_NUGGET + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_TIN_NUGGET = REGISTRY_FOLDER_NUGGET + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_NUGGET;

    // REGISTRY_NAME_ORE_CHUNK
    String REGISTRY_NAME_ALUMINUM_ORE_CHUNK = REGISTRY_FOLDER_ORE_CHUNK + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_COPPER_ORE_CHUNK = REGISTRY_FOLDER_ORE_CHUNK + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_GOLD_ORE_CHUNK = REGISTRY_FOLDER_ORE_CHUNK + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_IRON_ORE_CHUNK = REGISTRY_FOLDER_ORE_CHUNK + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_LEAD_ORE_CHUNK = REGISTRY_FOLDER_ORE_CHUNK + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_NICKEL_ORE_CHUNK = REGISTRY_FOLDER_ORE_CHUNK + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_SILVER_ORE_CHUNK = REGISTRY_FOLDER_ORE_CHUNK + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_TIN_ORE_CHUNK = REGISTRY_FOLDER_ORE_CHUNK + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_CHUNK;

    // REGISTRY_NAME_ORE_CLUMP
    String REGISTRY_NAME_ALUMINUM_ORE_CLUMP = REGISTRY_FOLDER_ORE_CLUMP + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_COPPER_ORE_CLUMP = REGISTRY_FOLDER_ORE_CLUMP + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_GOLD_ORE_CLUMP = REGISTRY_FOLDER_ORE_CLUMP + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_IRON_ORE_CLUMP = REGISTRY_FOLDER_ORE_CLUMP + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_LEAD_ORE_CLUMP = REGISTRY_FOLDER_ORE_CLUMP + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_NICKEL_ORE_CLUMP = REGISTRY_FOLDER_ORE_CLUMP + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_SILVER_ORE_CLUMP = REGISTRY_FOLDER_ORE_CLUMP + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_TIN_ORE_CLUMP = REGISTRY_FOLDER_ORE_CLUMP + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_CLUMP;

    // REGISTRY_NAME_ORE_CRYSTAL
    String REGISTRY_NAME_ALUMINUM_ORE_CRYSTAL = REGISTRY_FOLDER_ORE_CRYSTAL + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_COPPER_ORE_CRYSTAL = REGISTRY_FOLDER_ORE_CRYSTAL + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_GOLD_ORE_CRYSTAL = REGISTRY_FOLDER_ORE_CRYSTAL + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_IRON_ORE_CRYSTAL = REGISTRY_FOLDER_ORE_CRYSTAL + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_LEAD_ORE_CRYSTAL = REGISTRY_FOLDER_ORE_CRYSTAL + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_NICKEL_ORE_CRYSTAL = REGISTRY_FOLDER_ORE_CRYSTAL + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_SILVER_ORE_CRYSTAL = REGISTRY_FOLDER_ORE_CRYSTAL + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_TIN_ORE_CRYSTAL = REGISTRY_FOLDER_ORE_CRYSTAL + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;

    // REGISTRY_NAME_ORE_TINY_CRYSTAL
    String REGISTRY_NAME_ALUMINUM_ORE_TINY_CRYSTAL = REGISTRY_FOLDER_ORE_TINY_CRYSTAL + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_COPPER_ORE_TINY_CRYSTAL = REGISTRY_FOLDER_ORE_TINY_CRYSTAL + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_GOLD_ORE_TINY_CRYSTAL = REGISTRY_FOLDER_ORE_TINY_CRYSTAL + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_IRON_ORE_TINY_CRYSTAL = REGISTRY_FOLDER_ORE_TINY_CRYSTAL + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_LEAD_ORE_TINY_CRYSTAL = REGISTRY_FOLDER_ORE_TINY_CRYSTAL + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_NICKEL_ORE_TINY_CRYSTAL = REGISTRY_FOLDER_ORE_TINY_CRYSTAL + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_SILVER_ORE_TINY_CRYSTAL = REGISTRY_FOLDER_ORE_TINY_CRYSTAL + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_TIN_ORE_TINY_CRYSTAL = REGISTRY_FOLDER_ORE_TINY_CRYSTAL + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;

    // REGISTRY_NAME_ORE_DUST
    String REGISTRY_NAME_ALUMINUM_ORE_DUST = REGISTRY_FOLDER_ORE_DUST + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_COPPER_ORE_DUST = REGISTRY_FOLDER_ORE_DUST + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_GOLD_ORE_DUST = REGISTRY_FOLDER_ORE_DUST + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_IRON_ORE_DUST = REGISTRY_FOLDER_ORE_DUST + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_LEAD_ORE_DUST = REGISTRY_FOLDER_ORE_DUST + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_NICKEL_ORE_DUST = REGISTRY_FOLDER_ORE_DUST + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_SILVER_ORE_DUST = REGISTRY_FOLDER_ORE_DUST + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_TIN_ORE_DUST = REGISTRY_FOLDER_ORE_DUST + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_DUST;

    // REGISTRY_NAME_ORE_DIRTY_DUST
    String REGISTRY_NAME_ALUMINUM_ORE_DIRTY_DUST = REGISTRY_FOLDER_ORE_DIRTY_DUST + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_COPPER_ORE_DIRTY_DUST = REGISTRY_FOLDER_ORE_DIRTY_DUST + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_GOLD_ORE_DIRTY_DUST = REGISTRY_FOLDER_ORE_DIRTY_DUST + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_IRON_ORE_DIRTY_DUST = REGISTRY_FOLDER_ORE_DIRTY_DUST + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_LEAD_ORE_DIRTY_DUST = REGISTRY_FOLDER_ORE_DIRTY_DUST + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_NICKEL_ORE_DIRTY_DUST = REGISTRY_FOLDER_ORE_DIRTY_DUST + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_SILVER_ORE_DIRTY_DUST = REGISTRY_FOLDER_ORE_DIRTY_DUST + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_TIN_ORE_DIRTY_DUST = REGISTRY_FOLDER_ORE_DIRTY_DUST + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;

    // REGISTRY_NAME_ORE_FRAGMENT
    String REGISTRY_NAME_ALUMINUM_ORE_FRAGMENT = REGISTRY_FOLDER_ORE_FRAGMENT + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_COPPER_ORE_FRAGMENT = REGISTRY_FOLDER_ORE_FRAGMENT + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_GOLD_ORE_FRAGMENT = REGISTRY_FOLDER_ORE_FRAGMENT + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_IRON_ORE_FRAGMENT = REGISTRY_FOLDER_ORE_FRAGMENT + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_LEAD_ORE_FRAGMENT = REGISTRY_FOLDER_ORE_FRAGMENT + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_NICKEL_ORE_FRAGMENT = REGISTRY_FOLDER_ORE_FRAGMENT + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_SILVER_ORE_FRAGMENT = REGISTRY_FOLDER_ORE_FRAGMENT + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_TIN_ORE_FRAGMENT = REGISTRY_FOLDER_ORE_FRAGMENT + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;

    // REGISTRY_NAME_ORE_PIECE
    String REGISTRY_NAME_ALUMINUM_ORE_PIECE = REGISTRY_FOLDER_ORE_PIECE + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_COPPER_ORE_PIECE = REGISTRY_FOLDER_ORE_PIECE + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_GOLD_ORE_PIECE = REGISTRY_FOLDER_ORE_PIECE + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_IRON_ORE_PIECE = REGISTRY_FOLDER_ORE_PIECE + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_LEAD_ORE_PIECE = REGISTRY_FOLDER_ORE_PIECE + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_NICKEL_ORE_PIECE = REGISTRY_FOLDER_ORE_PIECE + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_SILVER_ORE_PIECE = REGISTRY_FOLDER_ORE_PIECE + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_TIN_ORE_PIECE = REGISTRY_FOLDER_ORE_PIECE + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_PIECE;

    // REGISTRY_NAME_ORE_PILE
    String REGISTRY_NAME_ALUMINUM_ORE_PILE = REGISTRY_FOLDER_ORE_PILE + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_COPPER_ORE_PILE = REGISTRY_FOLDER_ORE_PILE + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_GOLD_ORE_PILE = REGISTRY_FOLDER_ORE_PILE + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_IRON_ORE_PILE = REGISTRY_FOLDER_ORE_PILE + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_LEAD_ORE_PILE = REGISTRY_FOLDER_ORE_PILE + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_NICKEL_ORE_PILE = REGISTRY_FOLDER_ORE_PILE + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_SILVER_ORE_PILE = REGISTRY_FOLDER_ORE_PILE + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_TIN_ORE_PILE = REGISTRY_FOLDER_ORE_PILE + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_PILE;

    // REGISTRY_NAME_ORE_RESIDUAL
    String REGISTRY_NAME_ALUMINUM_ORE_RESIDUAL = REGISTRY_FOLDER_ORE_RESIDUAL + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_COPPER_ORE_RESIDUAL = REGISTRY_FOLDER_ORE_RESIDUAL + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_GOLD_ORE_RESIDUAL = REGISTRY_FOLDER_ORE_RESIDUAL + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_IRON_ORE_RESIDUAL = REGISTRY_FOLDER_ORE_RESIDUAL + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_LEAD_ORE_RESIDUAL = REGISTRY_FOLDER_ORE_RESIDUAL + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_NICKEL_ORE_RESIDUAL = REGISTRY_FOLDER_ORE_RESIDUAL + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_SILVER_ORE_RESIDUAL = REGISTRY_FOLDER_ORE_RESIDUAL + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_TIN_ORE_RESIDUAL = REGISTRY_FOLDER_ORE_RESIDUAL + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;

    // REGISTRY_NAME_ORE_SAND
    String REGISTRY_NAME_ALUMINUM_ORE_SAND = REGISTRY_FOLDER_ORE_SAND + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_COPPER_ORE_SAND = REGISTRY_FOLDER_ORE_SAND + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_GOLD_ORE_SAND = REGISTRY_FOLDER_ORE_SAND + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_IRON_ORE_SAND = REGISTRY_FOLDER_ORE_SAND + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_LEAD_ORE_SAND = REGISTRY_FOLDER_ORE_SAND + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_NICKEL_ORE_SAND = REGISTRY_FOLDER_ORE_SAND + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_SILVER_ORE_SAND = REGISTRY_FOLDER_ORE_SAND + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_TIN_ORE_SAND = REGISTRY_FOLDER_ORE_SAND + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_SAND;

    // REGISTRY_NAME_ORE_SHARD
    String REGISTRY_NAME_ALUMINUM_ORE_SHARD = REGISTRY_FOLDER_ORE_SHARD + REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_COPPER_ORE_SHARD = REGISTRY_FOLDER_ORE_SHARD + REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_GOLD_ORE_SHARD = REGISTRY_FOLDER_ORE_SHARD + REGISTRY_NAME_GOLD_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_IRON_ORE_SHARD = REGISTRY_FOLDER_ORE_SHARD + REGISTRY_NAME_IRON_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_LEAD_ORE_SHARD = REGISTRY_FOLDER_ORE_SHARD + REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_NICKEL_ORE_SHARD = REGISTRY_FOLDER_ORE_SHARD + REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_SILVER_ORE_SHARD = REGISTRY_FOLDER_ORE_SHARD + REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_TIN_ORE_SHARD = REGISTRY_FOLDER_ORE_SHARD + REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_SHARD;

    String REGISTRY_NAME_METAL_PRESS = "metal_press";

    String REGISTRY_NAME_CRUSHING_MACHINE = REGISTRY_NAME_CRUSHING + REGISTRY_NAME_MACHINE;
}
