package futuristicfactories.common.registry;

public interface IFFRegistryNames {

    String REGISTRY_NAME_ALUMINUM_MATERIAL = "aluminum";
    String REGISTRY_NAME_COPPER_MATERIAL = "copper";
    String REGISTRY_NAME_LEAD_MATERIAL = "lead";
    String REGISTRY_NAME_NICKEL_MATERIAL = "nickel";
    String REGISTRY_NAME_SILVER_MATERIAL = "silver";
    String REGISTRY_NAME_TIN_MATERIAL = "tin";

    String REGISTRY_NAME_ORE = "_ore";
    String REGISTRY_NAME_BLOCK = "_block";
    String REGISTRY_NAME_INGOT = "_ingot";
    String REGISTRY_NAME_NUGGET = "_nugget";

    String REGISTRY_NAME_ORE_CHUNK = "_ore_chunk";
    String REGISTRY_NAME_ORE_CLUMP = "_ore_clump";
    String REGISTRY_NAME_ORE_CRYSTAL = "_ore_crystal";
    String REGISTRY_NAME_ORE_TINY_CRYSTAL = "_ore_tiny_crystal";
    String REGISTRY_NAME_ORE_DUST = "_ore_dust";
    String REGISTRY_NAME_ORE_DIRTY_DUST = "_ore_dirty_dust";
    String REGISTRY_NAME_ORE_FRAGMENT = "_ore_fragment";
    String REGISTRY_NAME_ORE_PIECE = "_ore_piece";
    String REGISTRY_NAME_ORE_PILE = "_ore_pile";
    String REGISTRY_NAME_ORE_RESIDUAL = "_ore_residual";
    String REGISTRY_NAME_ORE_SAND = "_ore_sand";
    String REGISTRY_NAME_ORE_SHARD = "_ore_shard";

    String REGISTRY_NAME_SWORD = "_sword";
    String REGISTRY_NAME_AXE = "_axe";
    String REGISTRY_NAME_PICKAXE = "_pickaxe";
    String REGISTRY_NAME_SHOVEL = "_shovel";
    String REGISTRY_NAME_HOE = "_hoe";
    String REGISTRY_NAME_HELMET = "_helmet";
    String REGISTRY_NAME_CHESTPLATE = "_chestplate";
    String REGISTRY_NAME_PANTS = "_pants";
    String REGISTRY_NAME_BOOTS = "_boots";


    // REGISTRY_NAME_ORE
    String REGISTRY_NAME_ALUMINUM_ORE = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_COPPER_ORE = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_LEAD_ORE = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_NICKEL_ORE = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_SILVER_ORE = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE;
    String REGISTRY_NAME_TIN_ORE = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE;

    // REGISTRY_NAME_BLOCK

    String REGISTRY_NAME_ALUMINUM_BLOCK = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_COPPER_BLOCK = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_LEAD_BLOCK = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_NICKEL_BLOCK = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_SILVER_BLOCK = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_BLOCK;
    String REGISTRY_NAME_TIN_BLOCK = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_BLOCK;

    // REGISTRY_NAME_INGOT
    String REGISTRY_NAME_ALUMINUM_INGOT = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_COPPER_INGOT = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_LEAD_INGOT = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_NICKEL_INGOT = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_SILVER_INGOT = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_INGOT;
    String REGISTRY_NAME_TIN_INGOT = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_INGOT;

    // REGISTRY_NAME_NUGGET
    String REGISTRY_NAME_ALUMINUM_NUGGET = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_COPPER_NUGGET = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_LEAD_NUGGET = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_NICKEL_NUGGET = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_SILVER_NUGGET = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_NUGGET;
    String REGISTRY_NAME_TIN_NUGGET = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_NUGGET;

    // REGISTRY_NAME_ORE_CHUNK
    String REGISTRY_NAME_ALUMINUM_ORE_CHUNK = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_COPPER_ORE_CHUNK = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_LEAD_ORE_CHUNK = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_NICKEL_ORE_CHUNK = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_SILVER_ORE_CHUNK = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_CHUNK;
    String REGISTRY_NAME_TIN_ORE_CHUNK = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_CHUNK;

    // REGISTRY_NAME_ORE_CLUMP
    String REGISTRY_NAME_ALUMINUM_ORE_CLUMP = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_COPPER_ORE_CLUMP = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_LEAD_ORE_CLUMP = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_NICKEL_ORE_CLUMP = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_SILVER_ORE_CLUMP = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_CLUMP;
    String REGISTRY_NAME_TIN_ORE_CLUMP = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_CLUMP;

    // REGISTRY_NAME_ORE_CRYSTAL
    String REGISTRY_NAME_ALUMINUM_ORE_CRYSTAL = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_COPPER_ORE_CRYSTAL = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_LEAD_ORE_CRYSTAL = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_NICKEL_ORE_CRYSTAL = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_SILVER_ORE_CRYSTAL = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;
    String REGISTRY_NAME_TIN_ORE_CRYSTAL = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_CRYSTAL;

    // REGISTRY_NAME_ORE_TINY_CRYSTAL
    String REGISTRY_NAME_ALUMINUM_ORE_TINY_CRYSTAL = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_COPPER_ORE_TINY_CRYSTAL = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_LEAD_ORE_TINY_CRYSTAL = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_NICKEL_ORE_TINY_CRYSTAL = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_SILVER_ORE_TINY_CRYSTAL = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;
    String REGISTRY_NAME_TIN_ORE_TINY_CRYSTAL = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_TINY_CRYSTAL;

    // REGISTRY_NAME_ORE_DUST
    String REGISTRY_NAME_ALUMINUM_ORE_DUST = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_COPPER_ORE_DUST = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_LEAD_ORE_DUST = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_NICKEL_ORE_DUST = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_SILVER_ORE_DUST = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_DUST;
    String REGISTRY_NAME_TIN_ORE_DUST = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_DUST;

    // REGISTRY_NAME_ORE_DIRTY_DUST
    String REGISTRY_NAME_ALUMINUM_ORE_DIRTY_DUST = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_COPPER_ORE_DIRTY_DUST = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_LEAD_ORE_DIRTY_DUST = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_NICKEL_ORE_DIRTY_DUST = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_SILVER_ORE_DIRTY_DUST = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;
    String REGISTRY_NAME_TIN_ORE_DIRTY_DUST = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_DIRTY_DUST;

    // REGISTRY_NAME_ORE_FRAGMENT
    String REGISTRY_NAME_ALUMINUM_ORE_FRAGMENT = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_COPPER_ORE_FRAGMENT = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_LEAD_ORE_FRAGMENT = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_NICKEL_ORE_FRAGMENT = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_SILVER_ORE_FRAGMENT = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;
    String REGISTRY_NAME_TIN_ORE_FRAGMENT = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_FRAGMENT;

    // REGISTRY_NAME_ORE_PIECE
    String REGISTRY_NAME_ALUMINUM_ORE_PIECE = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_COPPER_ORE_PIECE = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_LEAD_ORE_PIECE = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_NICKEL_ORE_PIECE = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_SILVER_ORE_PIECE = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_PIECE;
    String REGISTRY_NAME_TIN_ORE_PIECE = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_PIECE;

    // REGISTRY_NAME_ORE_PILE
    String REGISTRY_NAME_ALUMINUM_ORE_PILE = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_COPPER_ORE_PILE = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_LEAD_ORE_PILE = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_NICKEL_ORE_PILE = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_SILVER_ORE_PILE = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_PILE;
    String REGISTRY_NAME_TIN_ORE_PILE = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_PILE;

    // REGISTRY_NAME_ORE_RESIDUAL
    String REGISTRY_NAME_ALUMINUM_ORE_RESIDUAL = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_COPPER_ORE_RESIDUAL = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_LEAD_ORE_RESIDUAL = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_NICKEL_ORE_RESIDUAL = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_SILVER_ORE_RESIDUAL = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;
    String REGISTRY_NAME_TIN_ORE_RESIDUAL = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_RESIDUAL;

    // REGISTRY_NAME_ORE_SAND
    String REGISTRY_NAME_ALUMINUM_ORE_SAND = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_COPPER_ORE_SAND = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_LEAD_ORE_SAND = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_NICKEL_ORE_SAND = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_SILVER_ORE_SAND = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_SAND;
    String REGISTRY_NAME_TIN_ORE_SAND = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_SAND;

    // REGISTRY_NAME_ORE_SHARD
    String REGISTRY_NAME_ALUMINUM_ORE_SHARD = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_COPPER_ORE_SHARD = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_LEAD_ORE_SHARD = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_NICKEL_ORE_SHARD = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_SILVER_ORE_SHARD = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_ORE_SHARD;
    String REGISTRY_NAME_TIN_ORE_SHARD = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_ORE_SHARD;

    // REGISTRY_NAME_SWORD
    String REGISTRY_NAME_ALUMINUM_SWORD = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_SWORD;
    String REGISTRY_NAME_COPPER_SWORD = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_SWORD;
    String REGISTRY_NAME_LEAD_SWORD = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_SWORD;
    String REGISTRY_NAME_NICKEL_SWORD = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_SWORD;
    String REGISTRY_NAME_SILVER_SWORD = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_SWORD;
    String REGISTRY_NAME_TIN_SWORD = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_SWORD;

    // REGISTRY_NAME_AXE
    String REGISTRY_NAME_ALUMINUM_AXE = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_AXE;
    String REGISTRY_NAME_COPPER_AXE = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_AXE;
    String REGISTRY_NAME_LEAD_AXE = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_AXE;
    String REGISTRY_NAME_NICKEL_AXE = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_AXE;
    String REGISTRY_NAME_SILVER_AXE = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_AXE;
    String REGISTRY_NAME_TIN_AXE = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_AXE;

    // REGISTRY_NAME_PICKAXE
    String REGISTRY_NAME_ALUMINUM_PICKAXE = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_PICKAXE;
    String REGISTRY_NAME_COPPER_PICKAXE = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_PICKAXE;
    String REGISTRY_NAME_LEAD_PICKAXE = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_PICKAXE;
    String REGISTRY_NAME_NICKEL_PICKAXE = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_PICKAXE;
    String REGISTRY_NAME_SILVER_PICKAXE = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_PICKAXE;
    String REGISTRY_NAME_TIN_PICKAXE = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_PICKAXE;

    // REGISTRY_NAME_SHOVEL
    String REGISTRY_NAME_ALUMINUM_SHOVEL = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_SHOVEL;
    String REGISTRY_NAME_COPPER_SHOVEL = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_SHOVEL;
    String REGISTRY_NAME_LEAD_SHOVEL = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_SHOVEL;
    String REGISTRY_NAME_NICKEL_SHOVEL = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_SHOVEL;
    String REGISTRY_NAME_SILVER_SHOVEL = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_SHOVEL;
    String REGISTRY_NAME_TIN_SHOVEL = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_SHOVEL;

    // REGISTRY_NAME_HOE
    String REGISTRY_NAME_ALUMINUM_HOE = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_HOE;
    String REGISTRY_NAME_COPPER_HOE = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_HOE;
    String REGISTRY_NAME_LEAD_HOE = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_HOE;
    String REGISTRY_NAME_NICKEL_HOE = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_HOE;
    String REGISTRY_NAME_SILVER_HOE = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_HOE;
    String REGISTRY_NAME_TIN_HOE = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_HOE;

    // REGISTRY_NAME_HELMET
    String REGISTRY_NAME_ALUMINUM_HELMET = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_HELMET;
    String REGISTRY_NAME_COPPER_HELMET = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_HELMET;
    String REGISTRY_NAME_LEAD_HELMET = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_HELMET;
    String REGISTRY_NAME_NICKEL_HELMET = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_HELMET;
    String REGISTRY_NAME_SILVER_HELMET = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_HELMET;
    String REGISTRY_NAME_TIN_HELMET = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_HELMET;

    // REGISTRY_NAME_CHESTPLATE
    String REGISTRY_NAME_ALUMINUM_CHESTPLATE = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_CHESTPLATE;
    String REGISTRY_NAME_COPPER_CHESTPLATE = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_CHESTPLATE;
    String REGISTRY_NAME_LEAD_CHESTPLATE = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_CHESTPLATE;
    String REGISTRY_NAME_NICKEL_CHESTPLATE = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_CHESTPLATE;
    String REGISTRY_NAME_SILVER_CHESTPLATE = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_CHESTPLATE;
    String REGISTRY_NAME_TIN_CHESTPLATE = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_CHESTPLATE;

    // REGISTRY_NAME_PANTS
    String REGISTRY_NAME_ALUMINUM_PANTS = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_PANTS;
    String REGISTRY_NAME_COPPER_PANTS = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_PANTS;
    String REGISTRY_NAME_LEAD_PANTS = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_PANTS;
    String REGISTRY_NAME_NICKEL_PANTS = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_PANTS;
    String REGISTRY_NAME_SILVER_PANTS = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_PANTS;
    String REGISTRY_NAME_TIN_PANTS = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_PANTS;

    // REGISTRY_NAME_BOOTS
    String REGISTRY_NAME_ALUMINUM_BOOTS = REGISTRY_NAME_ALUMINUM_MATERIAL + REGISTRY_NAME_BOOTS;
    String REGISTRY_NAME_COPPER_BOOTS = REGISTRY_NAME_COPPER_MATERIAL + REGISTRY_NAME_BOOTS;
    String REGISTRY_NAME_LEAD_BOOTS = REGISTRY_NAME_LEAD_MATERIAL + REGISTRY_NAME_BOOTS;
    String REGISTRY_NAME_NICKEL_BOOTS = REGISTRY_NAME_NICKEL_MATERIAL + REGISTRY_NAME_BOOTS;
    String REGISTRY_NAME_SILVER_BOOTS = REGISTRY_NAME_SILVER_MATERIAL + REGISTRY_NAME_BOOTS;
    String REGISTRY_NAME_TIN_BOOTS = REGISTRY_NAME_TIN_MATERIAL + REGISTRY_NAME_BOOTS;

    String REGISTRY_NAME_METAL_PRESS = "metal_press";
}
