@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package futuristicfactories.common.crafting.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;